# Generated by Django 4.2.5 on 2023-10-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
                ('category', models.CharField(choices=[('Photoshop', 'Photoshop'), ('Illustrator', 'Illustrator')], max_length=200, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('length', models.DurationField(null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('link', models.CharField(max_length=500, null=True)),
                ('thumbnail', models.ImageField(null=True, upload_to='./static/course')),
            ],
        ),
    ]
