# Generated by Django 4.2.6 on 2023-10-10 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_tutorial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
