# Generated by Django 4.2.6 on 2023-10-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_tutorial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('content1', models.TextField()),
                ('content2', models.TextField()),
                ('content3', models.TextField()),
                ('content4', models.TextField()),
                ('content5', models.TextField()),
                ('image1', models.ImageField(upload_to='./static/tutorial')),
                ('image2', models.ImageField(upload_to='./static/tutorial')),
                ('image3', models.ImageField(upload_to='./static/tutorial')),
                ('image4', models.ImageField(upload_to='./static/tutorial')),
                ('image5', models.ImageField(upload_to='./static/tutorial')),
            ],
        ),
    ]
