# Generated by Django 4.2.6 on 2023-10-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='category',
            field=models.CharField(choices=[('Photoshop', 'Photoshop'), ('Illustrator', 'Illustrator')], max_length=200, null=True),
        ),
    ]
