# Generated by Django 4.2.6 on 2023-10-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_tutorial_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='content1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='content2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='content3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='content4',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='content5',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='image1',
            field=models.ImageField(blank=True, upload_to='./static/tutorial'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='image2',
            field=models.ImageField(blank=True, upload_to='./static/tutorial'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='image3',
            field=models.ImageField(blank=True, upload_to='./static/tutorial'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='image4',
            field=models.ImageField(blank=True, upload_to='./static/tutorial'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='image5',
            field=models.ImageField(blank=True, upload_to='./static/tutorial'),
        ),
    ]
