# Generated by Django 4.2.6 on 2023-10-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_tutorialillustrator_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialillustrator',
            name='image2',
            field=models.ImageField(blank=True, upload_to='./static/tutorialIllustrator'),
        ),
        migrations.AlterField(
            model_name='tutorialillustrator',
            name='image3',
            field=models.ImageField(blank=True, upload_to='./static/tutorialIllustrator'),
        ),
        migrations.AlterField(
            model_name='tutorialillustrator',
            name='image4',
            field=models.ImageField(blank=True, upload_to='./static/tutorialIllustrator'),
        ),
        migrations.AlterField(
            model_name='tutorialillustrator',
            name='image5',
            field=models.ImageField(blank=True, upload_to='./static/tutorialIllustrator'),
        ),
    ]
