# Generated by Django 4.2.6 on 2023-12-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_tutorialillustrator_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialillustrator',
            name='image1',
            field=models.ImageField(blank=True, upload_to='./static/tutorialIllustrator/'),
        ),
        migrations.AlterField(
            model_name='tutorialillustrator',
            name='image2',
            field=models.ImageField(blank=True, upload_to='./static/tutorialIllustrator/'),
        ),
        migrations.AlterField(
            model_name='tutorialillustrator',
            name='image3',
            field=models.ImageField(blank=True, upload_to='./static/tutorialIllustrator/'),
        ),
        migrations.AlterField(
            model_name='tutorialillustrator',
            name='image4',
            field=models.ImageField(blank=True, upload_to='./static/tutorialIllustrator/'),
        ),
        migrations.AlterField(
            model_name='tutorialillustrator',
            name='image5',
            field=models.ImageField(blank=True, upload_to='./static/tutorialIllustrator/'),
        ),
        migrations.AlterField(
            model_name='tutorialphotoshop',
            name='image2',
            field=models.ImageField(blank=True, upload_to='./static/tutorial/'),
        ),
        migrations.AlterField(
            model_name='tutorialphotoshop',
            name='image3',
            field=models.ImageField(blank=True, upload_to='./static/tutorial/'),
        ),
        migrations.AlterField(
            model_name='tutorialphotoshop',
            name='image4',
            field=models.ImageField(blank=True, upload_to='./static/tutorial/'),
        ),
        migrations.AlterField(
            model_name='tutorialphotoshop',
            name='image5',
            field=models.ImageField(blank=True, upload_to='./static/tutorial/'),
        ),
    ]
