# Generated by Django 4.2.6 on 2024-02-16 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_tutorialillustrator_image1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
