# Generated by Django 4.2.6 on 2024-03-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_quiz_remove_course_link_course_url_customuserquizzes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='category',
            field=models.CharField(choices=[('Photoshop', 'Photoshop'), ('Illustrator', 'Illustrator')], max_length=200, null=True),
        ),
    ]
