# Generated by Django 4.2.6 on 2024-03-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_quiz_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='artist',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
