# Generated by Django 4.2.6 on 2024-03-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
