# Generated by Django 4.2.6 on 2024-03-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_quiz_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='category',
            field=models.CharField(choices=[('Photoshop', 'Photoshop'), ('Illustrator', 'Illustrator')], max_length=200, null=True),
        ),
    ]
