# Generated by Django 4.2.6 on 2024-03-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_quiz_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='courses',
            field=models.ManyToManyField(related_name='users', through='accounts.CustomUserCourses', to='accounts.course'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='quizzes',
            field=models.ManyToManyField(related_name='users', through='accounts.CustomUserQuizzes', to='accounts.quiz'),
        ),
    ]
