# Generated by Django 4.2.6 on 2024-03-07 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_customuser_courses_customuser_quizzes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='quizzes',
        ),
    ]
