# Generated by Django 4.2.6 on 2024-03-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_remove_customuserquizzes_quiz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='courses',
        ),
        migrations.AddField(
            model_name='customuser',
            name='courses',
            field=models.ManyToManyField(to='accounts.course'),
        ),
    ]
