# Generated by Django 4.2.6 on 2024-03-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_remove_customuser_courses_customuser_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='quizzes',
            field=models.ManyToManyField(to='accounts.quiz'),
        ),
    ]
