# Generated by Django 4.2.6 on 2024-03-17 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_customuser_quizzes'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='stripe_price_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
