# Generated by Django 4.2.6 on 2024-03-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
